apiVersion: apps/v1           # Version de l'API Kubernetes utilisée pour les applications
kind: Deployment              # Type d'objet : un déploiement pour gérer des Pods
metadata:
  name: mon-site-web-deployment # Nom unique du déploiement (SANS ESPACES)
spec:
  replicas: 2                 # Nombre de Pods (copies) identiques qu'on veut lancer en même temps
  selector:
    matchLabels:
      app: mon-site-web       # Étiquette (badge) pour que le Deployment reconnaisse ses Pods
  template:
    metadata:
      labels:
        app: mon-site-web     # Étiquette appliquée aux Pods créés
    spec:
      containers:
      - name: nginx           # Nom du conteneur à l'intérieur du Pod
        image: nginx:latest   # Image officielle Nginx téléchargée pour faire tourner le site
        ports:
        - containerPort: 80   # Le port interne où Nginx écoute dans le conteneur

---

apiVersion: v1                # Version de l'API Kubernetes de base (pour le réseau)
kind: Service                 # Type d'objet : un service pour exposer l'application
metadata:
  name: mon-site-web-service  # Nom unique du service (SANS ESPACES)
spec:
  type: NodePort              # Type de service qui ouvre un port externe sur la machine/VM
  selector:
    app: mon-site-web         # Doit correspondre à l'étiquette du Deployment pour cibler les bons Pods
  ports:
    - port: 80                # Port du service
      targetPort: 80          # Redirige le trafic vers le port 80 du conteneur
      nodePort: 30080         # Le port magique externe accessible via ton navigateur : http://<IP-VM>:30080